name: pyxenv
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8.6
  - pip=21.2.4
  - scikit-image=0.18.3
  - matplotlib=3.4.3
  - matplotlib-inline=0.1.3
  - matplotlib-scalebar=0.7.2
  - scikit-learn=0.24.2
  - lmfit=1.0.2
  - numpy=1.21.2
  - numba=0.53.1
  - psutil=5.8.0
  - ipywidgets=7.6.5
  - ipyevents=2.0.1
  - scipy=1.7.1
  - diffpy.structure=3.0.1
  - tqdm=4.62.2
  - transforms3d=0.3.1
  - orix=0.7.0
  - dask=2021.7.1
  - h5py=3.3.0
  - hyperspy=1.6.4
  - pywget=3.2
  - vtk=9.0.3
  - mayavi=4.7.2
